/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author oscar
 */
public class dlgNuevaCita extends javax.swing.JDialog {

    /**
     * Creates new form dlgNuevaCita
     */
    public dlgNuevaCita(java.awt.Frame parent, boolean modal, vAgendamiento vistaPadre) {
        super(parent, modal);
        initComponents();
        this.vistaPadre = vistaPadre;
        estilo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbPacientes = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbEspecialidad = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbMedico = new javax.swing.JComboBox();
        btGuardar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Ingrese los siguientes datos para agendar la cita");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Cedula Paciente:");

        txtCedula.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Paciente:");

        cbPacientes.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cbPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPacientesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Fecha:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel5.setText("AAAA-MM-DD");

        txtFecha.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Hora:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel7.setText("HH:MM");

        txtHora.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Especialidad:");

        cbEspecialidad.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setText("Medico:");

        cbMedico.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        btGuardar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btGuardar.setText("Guardar Cita");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btLimpiar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btGuardar)
                        .addGap(202, 202, 202)
                        .addComponent(btLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCedula)
                                    .addComponent(cbPacientes, 0, 221, Short.MAX_VALUE)
                                    .addComponent(txtFecha)
                                    .addComponent(txtHora)
                                    .addComponent(cbEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btCancelar)
                    .addComponent(btLimpiar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        comboPaciente pacienteSeleccionado = (comboPaciente) cbPacientes.getSelectedItem();
        String fecha = txtFecha.getText().trim();
        String hora = txtHora.getText().trim();

        if (pacienteSeleccionado == null || fecha.isEmpty() || hora.isEmpty()
                || fecha.equals("AAAA-MM-DD") || hora.equals("HH:MM")) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor complete todos los datos antes de guardar.",
                    "Campos Incompletos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Datos listos para guardar o pasar a vistaPadre / DAO:
        String cedula = pacienteSeleccionado.getCedula();
        String nombrePaciente = pacienteSeleccionado.getNombre();
        String especialidad = (String) cbEspecialidad.getSelectedItem();
        String medico = (String) cbMedico.getSelectedItem();

        javax.swing.JOptionPane.showMessageDialog(this,
                "Cita agendada exitosamente para " + nombrePaciente,
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        this.dispose();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        txtCedula.setText("");
        txtFecha.setText("");
        txtHora.setText("");

        cbPacientes.setSelectedIndex(-1);
        if (cbEspecialidad.getItemCount() > 0) {
            cbEspecialidad.setSelectedIndex(0);
        }
        if (cbMedico.getItemCount() > 0) {
            cbMedico.setSelectedIndex(0);
        }

        txtCedula.requestFocus();
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void cbPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPacientesActionPerformed
        // Obtener el paciente seleccionado
        comboPaciente seleccionado = (comboPaciente) cbPacientes.getSelectedItem();

        if (seleccionado != null) {
            // Asignar la cédula del paciente al campo de texto
            txtCedula.setText(seleccionado.getCedula());
        }
    }//GEN-LAST:event_cbPacientesActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        String cedulaIngresada = txtCedula.getText().trim();

        if (cedulaIngresada.isEmpty()) {
            cbPacientes.setSelectedIndex(-1); // Deseleccionar si está vacío
            return;
        }

        // Recorrer los ítems del combo para buscar la cédula coincidente
        for (int i = 0; i < cbPacientes.getItemCount(); i++) {
            comboPaciente p = (comboPaciente) cbPacientes.getItemAt(i);
            if (p != null && p.getCedula().equals(cedulaIngresada)) {
                cbPacientes.setSelectedIndex(i); // Selecciona al paciente si coincide la cédula
                return;
            }
        }

        // Si no encuentra coincidencia exacta, se deja sin selección
        cbPacientes.setSelectedIndex(-1);
    }//GEN-LAST:event_txtCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgNuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgNuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgNuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgNuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgNuevaCita dialog = new dlgNuevaCita(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JComboBox cbEspecialidad;
    private javax.swing.JComboBox cbMedico;
    private javax.swing.JComboBox cbPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
    private vAgendamiento vistaPadre;

    public void color() {
        this.getContentPane().setBackground(Color.WHITE);
        //Color de los botones
        btGuardar.setBackground(Color.decode("#A3C9A8"));
        btCancelar.setBackground(Color.decode("#A3C9A8"));
        btLimpiar.setBackground(Color.decode("#A3C9A8"));
    }

//Metodo para definir la combobox paciente pasar a modelos
    public class comboPaciente {

        private String cedula;
        private String nombre;

        public comboPaciente(String cedula, String nombre) {
            this.cedula = cedula;
            this.nombre = nombre;
        }

        public String getCedula() {
            return cedula;
        }

        public String getNombre() {
            return nombre;
        }

        // Este método define qué texto se mostrará en el ComboBox
        @Override
        public String toString() {
            return nombre;
        }
    }

//Metodo para las combobox de especialidad y medico
    public class ItemCombo {

        private int id;
        private String descripcion;

        public ItemCombo(int id, String descripcion) {
            this.id = id;
            this.descripcion = descripcion;
        }

        public int getId() {
            return id;
        }

        public String getDescripcion() {
            return descripcion;
        }

        @Override
        public String toString() {
            return descripcion; // Swing renderiza únicamente este texto en el combo
        }
    }

    private void cargarPacientes() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        // Aquí cargarías tus datos reales o de prueba
        model.addElement(new comboPaciente("", ""));
        model.addElement(new comboPaciente("12345678", "Juan Pérez"));
        model.addElement(new comboPaciente("87654321", "María López"));
        model.addElement(new comboPaciente("11223344", "Carlos Rodríguez"));

        cbPacientes.setModel(model);

        // Dejar selección vacía o por defecto si es necesario
        cbPacientes.setSelectedIndex(-1);
    }

//Configuracion de los combobox    
    private void configurarComboBoxes() {
        //Llenar combo de especialidades
        DefaultComboBoxModel<ItemCombo> modelEspecialidad = new DefaultComboBoxModel<>();
        modelEspecialidad.addElement(new ItemCombo(0, "Todas las especialidades"));
        modelEspecialidad.addElement(new ItemCombo(1, "Medicina General"));
        modelEspecialidad.addElement(new ItemCombo(2, "Pediatría"));
        modelEspecialidad.addElement(new ItemCombo(3, "Cardiología"));
        modelEspecialidad.addElement(new ItemCombo(4, "Odontología"));

        cbEspecialidad.setModel(modelEspecialidad);

        //Cargar médicos inicialmente con el filtro en 0 (Todos)
        cargarMedicosPorEspecialidad(0);

        //Listener para filtrar el combo de médicos al cambiar la especialidad
        cbEspecialidad.addActionListener(e -> {
            ItemCombo seleccion = (ItemCombo) cbEspecialidad.getSelectedItem();
            if (seleccion != null) {
                cargarMedicosPorEspecialidad(seleccion.getId());
            }
        });
    }

    private void cargarMedicosPorEspecialidad(int idEspecialidad) {
        DefaultComboBoxModel<ItemCombo> modelMedico = new DefaultComboBoxModel<>();
        modelMedico.addElement(new ItemCombo(0, "Todos los médicos"));

        // Simulación de filtro (Luego aquí consultarás a la Base de Datos según el ID)
        if (idEspecialidad == 0 || idEspecialidad == 1) {
            modelMedico.addElement(new ItemCombo(101, "Dr. Carlos Mendoza"));
        }
        if (idEspecialidad == 0 || idEspecialidad == 2) {
            modelMedico.addElement(new ItemCombo(102, "Dra. Ana Martínez"));
        }
        if (idEspecialidad == 0 || idEspecialidad == 3) {
            modelMedico.addElement(new ItemCombo(103, "Dr. Roberto Gómez"));
        }
        if (idEspecialidad == 0 || idEspecialidad == 4) {
            modelMedico.addElement(new ItemCombo(104, "Dra. Lucia Fernández"));
        }

        cbMedico.setModel(modelMedico);
    }

    public void prepararModoReagendar(String cedulaPaciente, String fechaActual, String horaActual) {
        // 1. Asignar y seleccionar al paciente existente
        txtCedula.setText(cedulaPaciente);

        // Disparar la búsqueda del paciente en el combo
        txtCedulaActionPerformed(null);

        // 2. Pre-cargar fecha y hora actuales
        txtFecha.setText(fechaActual);
        txtHora.setText(horaActual);

        // 3. Bloquear los campos del paciente para que no se alteren
        txtCedula.setEnabled(false);
        cbPacientes.setEnabled(false);

        // 4. Cambiar el título del botón o de la ventana (opcional)
        btGuardar.setText("Confirmar Reagendamiento");
        jLabel1.setText("Reagendar Cita Médica");
    }

    public void estilo(java.awt.Frame parent) {
        color();
        //Funcion de tamaño de la pantalla
        this.setSize(800, 550);
        //Funcion para mostrar el recuadro en el medio de la pantalla
        this.setLocationRelativeTo(parent);
        // Validar solo números en el campo de cédula 
        cargarPacientes();
        configurarComboBoxes();
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });
    }
}
