/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class vFacturacion extends javax.swing.JPanel {

    /**
     * Creates new form vFacturacion
     */
    public vFacturacion() {
        initComponents();
        estilo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtIngreso = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbFactura = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbPromedio = new javax.swing.JLabel();
        pGrafica = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btNuevaFactura = new javax.swing.JButton();
        btCambiar = new javax.swing.JButton();
        btExportar = new javax.swing.JButton();
        btGenerar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Ingrese el numero de cedula:");

        txtIngreso.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        btBuscar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Rango Fecha:");

        txtFecha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar)
                    .addComponent(txtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel11.setText("Datos del paciente");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total facturado");

        lbTotal.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lbTotal.setText("total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel2)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(lbTotal)
                    .addContainerGap(229, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(lbTotal)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Facturas pendientes");

        lbFactura.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lbFactura.setText("Fa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFactura)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Promedio por consulta");

        lbPromedio.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lbPromedio.setText("Pr");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lbPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPromedio)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);

        pGrafica.setBackground(new java.awt.Color(255, 255, 255));
        pGrafica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pGraficaLayout = new javax.swing.GroupLayout(pGrafica);
        pGrafica.setLayout(pGraficaLayout);
        pGraficaLayout.setHorizontalGroup(
            pGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        pGraficaLayout.setVerticalGroup(
            pGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel12.setText("Grafica de ingresos mensuales");

        tblFacturas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblFacturas.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N factura", "Fecha", "Paciente", "Cedula", "Servicio", "Monto", "Estado"
            }
        ));
        tblFacturas.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblFacturas);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel13.setText("Facturacion y cargos");

        btNuevaFactura.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btNuevaFactura.setText("Nueva Factura");
        btNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevaFacturaActionPerformed(evt);
            }
        });

        btCambiar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btCambiar.setText("Cambiar estado");
        btCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambiarActionPerformed(evt);
            }
        });

        btExportar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btExportar.setText("Exportar Excel");
        btExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportarActionPerformed(evt);
            }
        });

        btGenerar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btGenerar.setText("Generar reporte");
        btGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1641, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(btExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btNuevaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(pGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNuevaFactura)
                    .addComponent(btCambiar)
                    .addComponent(btGenerar)
                    .addComponent(btExportar))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        //Se va utilizar el siguiente metodo sorter que sirver para encontrar datos en especificos en la tabla
        if (tblFacturas.getRowSorter() == null) {
            return;
        }
        @SuppressWarnings("unchecked")
        javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter
                = (javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel>) tblFacturas.getRowSorter();
        //Se van a utilizar el campo de fecha y el de cedula
        String cedula = txtIngreso.getText().trim();
        String fecha = txtFecha.getText().trim();

        java.util.List<javax.swing.RowFilter<Object, Object>> filtros = new java.util.ArrayList<>();

        // Filtrar por cedula
        if (!cedula.isEmpty()) {
            filtros.add(javax.swing.RowFilter.regexFilter("(?i)" + cedula, 3));
        }
        // Filtrar por fecha 
        if (!fecha.isEmpty()) {
            filtros.add(javax.swing.RowFilter.regexFilter("(?i)" + fecha, 1));
        }

        //Aplicar filtro combinado o limpia si los campos estan vacios
        if (filtros.isEmpty()) {
            sorter.setRowFilter(null); // Muestra todos los datos
            btGenerar.setEnabled(false); // Deshabilita el botón porque no hay una búsqueda activa
        } else {
            sorter.setRowFilter(javax.swing.RowFilter.andFilter(filtros));
            // Habilita el botón SOLO si se buscó algo Y se encontraron resultados
            btGenerar.setEnabled(tblFacturas.getRowCount() > 0);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevaFacturaActionPerformed

    }//GEN-LAST:event_btNuevaFacturaActionPerformed

    private void btCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambiarActionPerformed
        int fila = tblFacturas.getSelectedRow();

        //Mensaje para el usuario 
        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una factura de la tabla para cambiar su estado.",
                    "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String numFactura = tblFacturas.getValueAt(fila, 0).toString();
        String estadoActual = tblFacturas.getValueAt(fila, 6).toString();

        //Opciones disponibles para el usuario
        String[] opciones = {"Pagado", "Anulado", "Pendiente"};

        String nuevoEstado = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione el nuevo estado para la factura " + numFactura + ":\n(Estado actual: " + estadoActual + ")",
                "Cambiar Estado de Factura",
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                estadoActual
        );

        if (nuevoEstado != null && !nuevoEstado.equals(estadoActual)) {
            // Actualizar la tabla
            tblFacturas.setValueAt(nuevoEstado, fila, 6);

            JOptionPane.showMessageDialog(this,
                    "El estado de la factura " + numFactura + " cambió a '" + nuevoEstado + "'.",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // (Opcional) Aquí puedes llamar a un método para recalcular los KPIs superiores
            // actualizarKPIs();
        }
    }//GEN-LAST:event_btCambiarActionPerformed

    private void btExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportarActionPerformed
        try {
            java.io.File pdfLocal = new java.io.File("src/archivos/reporte_ejemplo.pdf");
            if (pdfLocal.exists()) {
                java.awt.Desktop.getDesktop().open(pdfLocal);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cree la carpeta 'src/archivos' y coloque 'reporte_ejemplo.pdf' para la prueba.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir el PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btExportarActionPerformed

    private void btGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerarActionPerformed
        int filasVisibles = tblFacturas.getRowCount();

        if (filasVisibles == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No hay facturas visibles para generar el reporte.",
                    "Sin datos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double sumaTotal = 0;
        int pendientes = 0;

        for (int i = 0; i < filasVisibles; i++) {
            // Obtener el monto (Columna 5) quitando el símbolo 
            String montoTexto = tblFacturas.getValueAt(i, 5).toString().replace("$", "").trim();
            String estado = tblFacturas.getValueAt(i, 6).toString();

            try {
                sumaTotal += Double.parseDouble(montoTexto);
            } catch (NumberFormatException e) {
                // Ignorar errores de conversión si el formato varía
            }

            if (estado.equalsIgnoreCase("Pendiente")) {
                pendientes++;
            }
        }

        double promedio = sumaTotal / filasVisibles;

        // Mostrar el resumen del reporte
        String mensaje = String.format(
                "=== REPORTE DE FACTURACIÓN ===\n\n"
                + "• Total de registros procesados: %d\n"
                + "• Facturas pendientes: %d\n"
                + "• Monto total acumulado: $%.2f\n"
                + "• Promedio por consulta: $%.2f",
                filasVisibles, pendientes, sumaTotal, promedio
        );

        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Reporte Generado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCambiar;
    private javax.swing.JButton btExportar;
    private javax.swing.JButton btGenerar;
    private javax.swing.JButton btNuevaFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFactura;
    private javax.swing.JLabel lbPromedio;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JPanel pGrafica;
    private javax.swing.JTable tblFacturas;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIngreso;
    // End of variables declaration//GEN-END:variables

    //Funcion para el color de los objetos
    public void color() {
        this.setBackground(java.awt.Color.WHITE);
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        //Cambiar el color de cuando se seleciona una fila
        tblFacturas.setSelectionBackground(Color.decode("#C8E6C9"));
        //Cambiar el color de las letras en la selecccion de fila
        tblFacturas.setSelectionForeground(Color.BLACK);
        btBuscar.setBackground(java.awt.Color.decode("#A3C9A8"));
        btCambiar.setBackground(java.awt.Color.decode("#A3C9A8"));
        btExportar.setBackground(java.awt.Color.decode("#A3C9A8"));
        btGenerar.setBackground(java.awt.Color.decode("#A3C9A8"));
        btNuevaFactura.setBackground(java.awt.Color.decode("#A3C9A8"));

    }

    public void estilo() {
        color();
        btCambiar.setEnabled(false);
        btGenerar.setEnabled(false);

        //Bloquear celdas de las tablas y que las filas esten vacias
        javax.swing.table.DefaultTableModel modelFacturas = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"N factura", "Fecha", "Paciente", "Cedula", "Servicio", "Monto", "Estado"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea la edición
            }
        };
        tblFacturas.setModel(modelFacturas);
        //Sirve para filtar informacion de las tablas
        tblFacturas.setRowSorter(new javax.swing.table.TableRowSorter<>(modelFacturas));
        //Metodo para cuando se selecione una fila se pueda cambiar el estado
        tblFacturas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                boolean seleccionada = tblFacturas.getSelectedRow() != -1;
                btCambiar.setEnabled(seleccionada);
            }
        });
        // Insertar cedula y fecha cuando se hace clic en la tabla
        tblFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = tblFacturas.getSelectedRow();
                if (fila != -1) {
                    // Columna 1: Fecha
                    String fecha = tblFacturas.getValueAt(fila, 1).toString();
                    // Columna 2: Paciente / Cédula
                    String pacienteCedula = tblFacturas.getValueAt(fila, 3).toString();

                    // Cargar los valores en las casillas de texto
                    txtFecha.setText(fecha);
                    txtIngreso.setText(pacienteCedula);
                }
            }
        });

        // Validar solo números en el campo de cédula 
        txtIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });
        configurarTarjetas();
        cargarDatos();
    }

    //Datos de prueba para las tarjetas
    private void configurarTarjetas() {
        //Agregar metodos
        //Datos de prueba
        int total = 1200000;
        int pendiente = 5;
        int promedio = 12000;
        lbTotal.setText(String.valueOf(total));
        lbFactura.setText(String.valueOf(pendiente));
        lbPromedio.setText(String.valueOf(promedio));
    }

    //Datos de prueba para la tabla
    private void cargarDatos() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblFacturas.getModel();
        model.setRowCount(0); // Limpiar filas por defecto

        // Filas de prueba
        model.addRow(new Object[]{"FAC-001", "18/09/2026", "Carlos Ruiz", "1054", "Consulta General", "$150.00", "Pagado"});
        model.addRow(new Object[]{"FAC-002", "18/09/2026", "María Gómez", "1011", "Laboratorio", "$85.00", "Pendiente"});
        model.addRow(new Object[]{"FAC-003", "17/09/2026", "Juan Pérez", "1015", "Radiología", "$210.00", "Pagado"});

    }
}
