/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Modelo.cPaciente;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author admin
 */
public class vPacientes extends javax.swing.JFrame {

    private class FiltroDocumento extends DocumentFilter {

        @Override
        public void insertString(FilterBypass fb, int offset,
                String texto, AttributeSet atributos)
                throws BadLocationException {

            replace(fb, offset, 0, texto, atributos);
        }

        @Override
        public void remove(FilterBypass fb, int offset, int longitud)
                throws BadLocationException {

            replace(fb, offset, longitud, "", null);
        }

        @Override
        public void replace(FilterBypass fb, int offset, int longitud,
                String texto, AttributeSet atributos)
                throws BadLocationException {

            if (texto == null) {
                texto = "";
            }

            // Admitir números y puntos, incluso al pegar un documento.
            // Si hay letras u otros caracteres, rechazar el cambio.
            if (!texto.matches("[0-9.]*")) {
                return;
            }

            String actual = fb.getDocument().getText(
                    0, fb.getDocument().getLength()
            );

            // Si se intenta borrar solamente un punto,
            // borrar también el dígito de su lado.
            if (texto.isEmpty() && longitud == 1
                    && actual.charAt(offset) == '.') {

                if (txtNumeroDocumento.getCaretPosition() > offset
                        && offset > 0) {
                    offset--;
                    longitud++;
                } else if (offset + 1 < actual.length()) {
                    longitud++;
                }
            }

            String izquierda = actual.substring(0, offset);
            String derecha = actual.substring(offset + longitud);

            String digitosIzquierda = izquierda.replace(".", "");
            String digitosNuevos = texto.replace(".", "");

            String numero = digitosIzquierda
                    + digitosNuevos
                    + derecha.replace(".", "");

            // Insertar un punto cada tres dígitos desde la derecha.
            StringBuilder formato = new StringBuilder();

            for (int i = 0; i < numero.length(); i++) {
                if (i > 0 && (numero.length() - i) % 3 == 0) {
                    formato.append('.');
                }

                formato.append(numero.charAt(i));
            }

            fb.replace(
                    0,
                    fb.getDocument().getLength(),
                    formato.toString(),
                    atributos
            );

            // Mantener el cursor junto a los dígitos que se editaron.
            int digitosAntes = digitosIzquierda.length()
                    + digitosNuevos.length();

            int posicion = 0;
            int contados = 0;

            while (posicion < formato.length()
                    && contados < digitosAntes) {

                if (formato.charAt(posicion) != '.') {
                    contados++;
                }

                posicion++;
            }

            txtNumeroDocumento.setCaretPosition(posicion);
        }
    }
    private final cPaciente modeloPaciente = new cPaciente();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vPacientes.class.getName());

    /**
     * Creates new form vPacientes
     */
    public vPacientes() {
        initComponents();

        estilo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btNuevo = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtTipoSangre = new javax.swing.JTextField();
        txtFactor = new javax.swing.JTextField();
        cbSexo = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 246, 248));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText("Apellidos:");

        txtNombres.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setText("Nombres:");

        txtApellidos.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtApellidos.addActionListener(this::txtApellidosActionPerformed);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setText("Tipo de Documento:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setText("Número de Documento:");

        txtNumeroDocumento.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtNumeroDocumento.addActionListener(this::txtNumeroDocumentoActionPerformed);

        btBuscar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btBuscar.setForeground(new java.awt.Color(55, 65, 81));
        btBuscar.setText("Buscar ");
        btBuscar.addActionListener(this::btBuscarActionPerformed);

        btNuevo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btNuevo.setForeground(new java.awt.Color(55, 65, 81));
        btNuevo.setText("Cancelar");
        btNuevo.addActionListener(this::btNuevoActionPerformed);

        btGuardar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btGuardar.setText("Guardar ");
        btGuardar.addActionListener(this::btGuardarActionPerformed);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 41, 55));
        jLabel5.setText("Pacientes");
        jLabel5.setAlignmentY(0.0F);

        cmbTipoDocumento.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmbTipoDocumento.setEditor(null);
        cmbTipoDocumento.addActionListener(this::cmbTipoDocumentoActionPerformed);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel6.setText("Factor rh:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel7.setText("Fecha de nacimiento:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel8.setText("Tipo de sangre:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel9.setText("Sexo:");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel10.setText("Telefono:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel11.setText("Correo:");

        txtFechaNacimiento.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFechaNacimiento.addActionListener(this::txtFechaNacimientoActionPerformed);

        txtTipoSangre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtTipoSangre.addActionListener(this::txtTipoSangreActionPerformed);

        txtFactor.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFactor.addActionListener(this::txtFactorActionPerformed);

        cbSexo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cbSexo.setEditor(null);
        cbSexo.addActionListener(this::cbSexoActionPerformed);

        txtTelefono.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtTelefono.addActionListener(this::txtTelefonoActionPerformed);

        txtCorreo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtCorreo.addActionListener(this::txtCorreoActionPerformed);

        btActualizar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(this::btActualizarActionPerformed);

        tblPacientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPacientes.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblPacientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(623, 623, 623))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTipoSangre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(48, 48, 48)
                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbSexo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFactor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtApellidos)
                                .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(jLabel4))
                            .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDocumentoActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        String nombres = txtNombres.getText().trim();
        String apellidos = txtApellidos.getText().trim();
        String tipo = cmbTipoDocumento.getSelectedIndex() == 0
                ? ""
                : cmbTipoDocumento.getSelectedItem().toString();
        String numero = txtNumeroDocumento.getText().replace(".", "").trim();
        String fechaNac = txtFechaNacimiento.getText().trim();
        String tipoSangre = txtTipoSangre.getText().trim();
        String factorRh = txtFactor.getText().trim();
        String sexo = cbSexo.getSelectedIndex() == 0
                ? ""
                : cbSexo.getSelectedItem().toString();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim(); 
        java.time.LocalDateTime ahora = java.time.LocalDateTime.now();
        java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String fechaCreacion = ahora.format(formato);
        
        if (nombres.isEmpty() || apellidos.isEmpty()
                || tipo.isEmpty() || numero.isEmpty() || fechaNac.isEmpty() || tipoSangre.isEmpty() || factorRh.isEmpty() || sexo.isEmpty() 
                || telefono.isEmpty() || correo.isEmpty() || fechaCreacion.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Completa nombres, apellidos, tipo y numero de documento.",
                    "Faltan datos",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            cPaciente datos = new cPaciente(
                    nombres, 
                    apellidos, 
                    tipo, 
                    numero, 
                    fechaNac, 
                    tipoSangre, 
                    factorRh, 
                    sexo, 
                    telefono, 
                    correo, 
                    fechaCreacion
            );

            long id = modeloPaciente.registrarConHistoria(datos);

            // El método solo devuelve el ID después de confirmar el guardado.
            JOptionPane.showMessageDialog(
                    this,
                    "Paciente e historia guardados correctamente.\n"
                    + "ID del paciente: " + id + "\n"
                    + "Numero de historia: HC" + id,
                    "Registro guardado",
                    JOptionPane.INFORMATION_MESSAGE
            );

            // Evita intentar guardar nuevamente el mismo registro.
            btGuardar.setEnabled(false);
            modeloPaciente.mostrarPacientes(tblPacientes);

        } catch (IllegalArgumentException error) {

            JOptionPane.showMessageDialog(
                    this,
                    error.getMessage(),
                    "Revisa los datos",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (SQLException error) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo completar el registro.\n" + error.getMessage(),
                    "Error al guardar",
                    JOptionPane.ERROR_MESSAGE
            );
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
// 1. Crear los componentes internos del diálogo
        String[] criterios = {"Número de Documento", "Nombres", "Apellidos", "Tipo de sangre", "Correo"};
        javax.swing.JComboBox<String> cbCriterio = new javax.swing.JComboBox<>(criterios);
        javax.swing.JTextField txtBusqueda = new javax.swing.JTextField();

        // 2. Agrupar los componentes dentro de un panel para el JOptionPane
        Object[] formulario = {
            "Seleccione el criterio de búsqueda:", cbCriterio,
            "Ingrese el valor a buscar:", txtBusqueda
        };

        // 3. Mostrar el JOptionPane emergente
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                formulario,
                "Buscar Paciente",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        // 4. Procesar la respuesta
        if (opcion == javax.swing.JOptionPane.OK_OPTION) {
            String texto = txtBusqueda.getText().trim();

            // Si el usuario deja la búsqueda vacía, quitar el filtro
            if (texto.isEmpty()) {
                quitarFiltroTabla(); // Asegúrate de que este método apunte a tblPacientes
                return;
            }

            // Determinar cuál columna de la tabla corresponde al criterio seleccionado
            // Columnas según tu tabla: 1: Número documento, 2: Nombres, 3: Apellidos, 5: Tipo de sangre, 9: Correo
            int columnaIndex = 1; // Valor por defecto
            String criterioSeleccionado = (String) cbCriterio.getSelectedItem();

            switch (criterioSeleccionado) {
                case "Número de Documento":
                    columnaIndex = 1;
                    break;
                case "Nombres":
                    columnaIndex = 2;
                    break;
                case "Apellidos":
                    columnaIndex = 3;
                    break;
                case "Tipo de sangre":
                    columnaIndex = 5;
                    break;
                case "Correo":
                    columnaIndex = 9;
                    break;
            }

            // Aplicar el filtro a la JTable (insensible a mayúsculas/minúsculas)
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPacientes.getModel();
            javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(model);
            tblPacientes.setRowSorter(sorter);

            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + java.util.regex.Pattern.quote(texto), columnaIndex));

            // Si no hay coincidencias, notificar al usuario
            if (tblPacientes.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se encontraron pacientes para: " + texto,
                        "Sin resultados",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btNuevoActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void cmbTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoDocumentoActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtTipoSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoSangreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoSangreActionPerformed

    private void txtFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFactorActionPerformed

    private void cbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed

    String tipoDoc = cmbTipoDocumento.getSelectedItem().toString();
    String numDoc = txtNumeroDocumento.getText().trim().replace(".", "");
    String nombres = txtNombres.getText().trim();
    String apellidos = txtApellidos.getText().trim();
    String fechaNac = txtFechaNacimiento.getText().trim();
    String grupoSang = txtTipoSangre.getText().trim();
    String factorRh = txtFactor.getText().trim();
    String sexo = cbSexo.getSelectedItem().toString();
    String telefono = txtTelefono.getText().trim();
    String correo = txtCorreo.getText().trim();

    if (numDoc.isEmpty() || nombres.isEmpty() || apellidos.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
            this, 
            "Por favor, complete al menos el documento, nombres y apellidos.", 
            "Campos obligatorios", 
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "¿Está seguro de que desea actualizar los datos del paciente con documento " + numDoc + "?", 
        "Confirmar Actualización", 
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        // 4. Instanciar el modelo y ejecutar la actualización
        cPaciente pacienteModelo = new cPaciente();
        boolean actualizado = pacienteModelo.actualizarPaciente(
            tipoDoc, numDoc, nombres, apellidos, fechaNac, grupoSang, factorRh, sexo, telefono, correo
        );

        // 5. Manejar el resultado devuelto por la base de datos
        if (actualizado) {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Paciente actualizado correctamente.", 
                "Éxito", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            // Refrescar la tabla con los nuevos datos
            btGuardar.setEnabled(false);
            pacienteModelo.mostrarPacientes(tblPacientes);

            // Limpiar los filtros si existía alguno aplicado
            quitarFiltroTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "No se encontró un paciente registrado con el documento: " + numDoc, 
                "Error al actualizar", 
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }
    }//GEN-LAST:event_btActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vPacientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFactor;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroDocumento;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoSangre;
    // End of variables declaration//GEN-END:variables

    public void color() {
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        //Cambiar el color de cuando se seleciona una fila
        tblPacientes.setSelectionBackground(Color.decode("#C8E6C9"));
        //Cambiar el color de las letras en la selecccion de fila
        tblPacientes.setSelectionForeground(Color.BLACK);
        btGuardar.setBackground(java.awt.Color.decode("#A3C9A8"));
        btActualizar.setBackground(java.awt.Color.decode("#A3C9A8"));
        btNuevo.setBackground(java.awt.Color.decode("#A3C9A8"));
        btBuscar.setBackground(java.awt.Color.decode("#A3C9A8"));
    }
    
    

    public void estilo() {
        color();
        cmbTipoDocumento.setEditable(false);
        cmbTipoDocumento.setEditor(
                new javax.swing.plaf.basic.BasicComboBoxEditor()
        );
        cmbTipoDocumento.setModel(new DefaultComboBoxModel<>(
                new String[]{
                    "Seleccione...",
                    "CC", "TI", "CE", "RC", "CN",
                    "PA", "CD", "SC", "PE", "PT",
                    "PPT", "DE", "PC", "AS", "MS", "SI"
                }
        ));

        ((AbstractDocument) txtNumeroDocumento.getDocument())
                .setDocumentFilter(new FiltroDocumento());
        cbSexo.setEditable(false);
        cbSexo.setEditor(
                new javax.swing.plaf.basic.BasicComboBoxEditor()
        );
        cbSexo.setModel(new DefaultComboBoxModel<>(
                new String[]{
                    "Seleccione...",
                    "Hombre", "Mujer", "Otro",}
        ));
        
        cPaciente paciente = new cPaciente();
        paciente.mostrarPacientes(tblPacientes);
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = tblPacientes.getSelectedRow();
                if (fila >= 0) {
                    cmbTipoDocumento.setSelectedItem(tblPacientes.getValueAt(fila, 0).toString());
                    txtNumeroDocumento.setText(tblPacientes.getValueAt(fila, 1).toString());
                    txtNombres.setText(tblPacientes.getValueAt(fila, 2).toString());
                    txtApellidos.setText(tblPacientes.getValueAt(fila, 3).toString());
                    txtFechaNacimiento.setText(tblPacientes.getValueAt(fila, 4).toString());
                    txtTipoSangre.setText(tblPacientes.getValueAt(fila, 5).toString());
                    txtFactor.setText(tblPacientes.getValueAt(fila, 6).toString());
                    cbSexo.setSelectedItem(tblPacientes.getValueAt(fila, 7).toString());;
                    txtTelefono.setText(tblPacientes.getValueAt(fila, 8).toString());
                    txtCorreo.setText(tblPacientes.getValueAt(fila, 9).toString());
                }
            }
        });
        // Validar solo números en el campo de cédula 
        txtNumeroDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });
    }
    
    private void quitarFiltroTabla() {
    // Verifica si la tabla tiene un filtro aplicado
    if (tblPacientes.getRowSorter() != null) {
        // Le asigna un filtro "nulo", lo que significa que borra el filtro y muestra todo
        ((javax.swing.table.TableRowSorter) tblPacientes.getRowSorter()).setRowFilter(null);
    } 
}
    
        private void limpiarCampos() {
        txtNombres.setText("");
        txtApellidos.setText("");
        cmbTipoDocumento.setSelectedIndex(0);
        txtNumeroDocumento.setText("");
        txtFechaNacimiento.setText("");
        txtTipoSangre.setText("");
        txtFactor.setText("");
        cbSexo.setSelectedIndex(0);
        txtTelefono.setText("");
        txtCorreo.setText("");
        btGuardar.setEnabled(true);
        txtNombres.requestFocusInWindow();        // TODO add your handling code here:
        tblPacientes.clearSelection();
    }

}
