/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Modelo.cPaciente;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author admin
 */
public class vPacientes extends javax.swing.JFrame {

    private class FiltroDocumento extends DocumentFilter {

        @Override
        public void insertString(FilterBypass fb, int offset,
                String texto, AttributeSet atributos)
                throws BadLocationException {

            replace(fb, offset, 0, texto, atributos);
        }

        @Override
        public void remove(FilterBypass fb, int offset, int longitud)
                throws BadLocationException {

            replace(fb, offset, longitud, "", null);
        }

        @Override
        public void replace(FilterBypass fb, int offset, int longitud,
                String texto, AttributeSet atributos)
                throws BadLocationException {

            if (texto == null) {
                texto = "";
            }

            // Admitir números y puntos, incluso al pegar un documento.
            // Si hay letras u otros caracteres, rechazar el cambio.
            if (!texto.matches("[0-9.]*")) {
                return;
            }

            String actual = fb.getDocument().getText(
                    0, fb.getDocument().getLength()
            );

            // Si se intenta borrar solamente un punto,
            // borrar también el dígito de su lado.
            if (texto.isEmpty() && longitud == 1
                    && actual.charAt(offset) == '.') {

                if (txtNumeroDocumento.getCaretPosition() > offset
                        && offset > 0) {
                    offset--;
                    longitud++;
                } else if (offset + 1 < actual.length()) {
                    longitud++;
                }
            }

            String izquierda = actual.substring(0, offset);
            String derecha = actual.substring(offset + longitud);

            String digitosIzquierda = izquierda.replace(".", "");
            String digitosNuevos = texto.replace(".", "");

            String numero = digitosIzquierda
                    + digitosNuevos
                    + derecha.replace(".", "");

            // Insertar un punto cada tres dígitos desde la derecha.
            StringBuilder formato = new StringBuilder();

            for (int i = 0; i < numero.length(); i++) {
                if (i > 0 && (numero.length() - i) % 3 == 0) {
                    formato.append('.');
                }

                formato.append(numero.charAt(i));
            }

            fb.replace(
                    0,
                    fb.getDocument().getLength(),
                    formato.toString(),
                    atributos
            );

            // Mantener el cursor junto a los dígitos que se editaron.
            int digitosAntes = digitosIzquierda.length()
                    + digitosNuevos.length();

            int posicion = 0;
            int contados = 0;

            while (posicion < formato.length()
                    && contados < digitosAntes) {

                if (formato.charAt(posicion) != '.') {
                    contados++;
                }

                posicion++;
            }

            txtNumeroDocumento.setCaretPosition(posicion);
        }
    }
    private final cPaciente modeloPaciente = new cPaciente();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vPacientes.class.getName());

    /**
     * Creates new form vPacientes
     */
    public vPacientes() {
        initComponents();
        cmbTipoDocumento.setEditable(false);
cmbTipoDocumento.setEditor(
        new javax.swing.plaf.basic.BasicComboBoxEditor()
);
        cmbTipoDocumento.setModel(new DefaultComboBoxModel<>(
                new String[]{
                    "Seleccione...",
                    "CC", "TI", "CE", "RC", "CN",
                    "PA", "CD", "SC", "PE", "PT",
                    "PPT", "DE", "PC", "AS", "MS", "SI"
                }
        ));

        ((AbstractDocument) txtNumeroDocumento.getDocument())
                .setDocumentFilter(new FiltroDocumento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btNuevo = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTipoDocumento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 246, 248));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Apellidos");

        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombres");

        txtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidos.addActionListener(this::txtApellidosActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de Documento");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Número de Documento");

        txtNumeroDocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumeroDocumento.addActionListener(this::txtNumeroDocumentoActionPerformed);

        btBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscar.setForeground(new java.awt.Color(55, 65, 81));
        btBuscar.setText("Buscar Paciente");
        btBuscar.addActionListener(this::btBuscarActionPerformed);

        btNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btNuevo.setForeground(new java.awt.Color(55, 65, 81));
        btNuevo.setText("Nuevo / Limpiar");
        btNuevo.addActionListener(this::btNuevoActionPerformed);

        btGuardar.setBackground(new java.awt.Color(37, 99, 235));
        btGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btGuardar.setText("Guardar Paciente");
        btGuardar.addActionListener(this::btGuardarActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 41, 55));
        jLabel5.setText("GESTIÓN DE PACIENTES");
        jLabel5.setAlignmentY(0.0F);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 114, 128));
        jLabel6.setText("Consulta y registra la información del paciente");

        cmbTipoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoDocumento.setEditor(null);
        cmbTipoDocumento.addActionListener(this::cmbTipoDocumentoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btGuardar)
                        .addGap(104, 104, 104)
                        .addComponent(btBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNuevo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellidos)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoDocumento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDocumentoActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        String nombres = txtNombres.getText().trim();
        String apellidos = txtApellidos.getText().trim();
        String tipo = cmbTipoDocumento.getSelectedIndex() == 0
                ? ""
                : cmbTipoDocumento.getSelectedItem().toString();

        String numero = txtNumeroDocumento.getText().replace(".", "").trim();

        if (nombres.isEmpty() || apellidos.isEmpty()
                || tipo.isEmpty() || numero.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Completa nombres, apellidos, tipo y numero de documento.",
                    "Faltan datos",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            cPaciente datos = new cPaciente(
                    nombres,
                    apellidos,
                    tipo,
                    numero
            );

            long id = modeloPaciente.registrarConHistoria(datos);

            // El método solo devuelve el ID después de confirmar el guardado.
            JOptionPane.showMessageDialog(
                    this,
                    "Paciente e historia guardados correctamente.\n"
                    + "ID del paciente: " + id + "\n"
                    + "Numero de historia: HC" + id,
                    "Registro guardado",
                    JOptionPane.INFORMATION_MESSAGE
            );

            // Evita intentar guardar nuevamente el mismo registro.
            btGuardar.setEnabled(false);

        } catch (IllegalArgumentException error) {

            JOptionPane.showMessageDialog(
                    this,
                    error.getMessage(),
                    "Revisa los datos",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (SQLException error) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo completar el registro.\n" + error.getMessage(),
                    "Error al guardar",
                    JOptionPane.ERROR_MESSAGE
            );
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String tipo = cmbTipoDocumento.getSelectedIndex() == 0
                ? ""
                : cmbTipoDocumento.getSelectedItem().toString();

        String numero = txtNumeroDocumento.getText().replace(".", "").trim();

        if (tipo.isEmpty() || numero.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Escribe el tipo y el numero de documento para buscar.",
                    "Faltan datos",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            cPaciente paciente = modeloPaciente.buscarPorDocumento(tipo, numero);

            if (paciente == null) {

                // Quita los nombres de una búsqueda anterior.
                txtNombres.setText("");
                txtApellidos.setText("");

                btGuardar.setEnabled(true);

                JOptionPane.showMessageDialog(
                        this,
                        "No existe un paciente con ese tipo y numero de documento.",
                        "Sin resultados",
                        JOptionPane.INFORMATION_MESSAGE
                );

                return;
            }

            // Llena los campos con información que viene de SQLite.
            txtNombres.setText(paciente.getNombres());
            txtApellidos.setText(paciente.getApellidos());
            cmbTipoDocumento.setSelectedItem(paciente.getTipoDocumento());
            txtNumeroDocumento.setText(paciente.getNumeroDocumento());

            // Buscar muestra un registro existente; no crea uno nuevo.
            btGuardar.setEnabled(false);

        } catch (IllegalArgumentException error) {

            JOptionPane.showMessageDialog(
                    this,
                    error.getMessage(),
                    "Revisa el documento",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (SQLException error) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo realizar la busqueda.\n" + error.getMessage(),
                    "Error al buscar",
                    JOptionPane.ERROR_MESSAGE
            );
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        txtNombres.setText("");
        txtApellidos.setText("");
        cmbTipoDocumento.setSelectedIndex(0);
        txtNumeroDocumento.setText("");

        btGuardar.setEnabled(true);
        txtNombres.requestFocusInWindow();        // TODO add your handling code here:
    }//GEN-LAST:event_btNuevoActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void cmbTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vPacientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroDocumento;
    // End of variables declaration//GEN-END:variables
}
