/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author oscar
 */
public class vPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vPrincipal
     */
    public vPrincipal() {
        initComponents();
        estilo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        btInicio = new javax.swing.JButton();
        btHistoria = new javax.swing.JButton();
        btLaboratorio = new javax.swing.JButton();
        btPACS = new javax.swing.JButton();
        btFacturacion = new javax.swing.JButton();
        btCerrar = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        btAgenda = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        pBase = new javax.swing.JPanel();
        pInicio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pPacienteHoy = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbCantidadDia = new javax.swing.JLabel();
        pPacientesEspera = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbCantidadPendientes = new javax.swing.JLabel();
        pAlerta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbCantidadAlerta = new javax.swing.JLabel();
        pPendiente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbCantidadIA = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        pPerfil = new javax.swing.JPanel();
        lbBienvenida = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        lbFechaHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(51, 255, 51));

        btInicio.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btInicio.setText("Inicio");
        btInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btInicio.setBorderPainted(false);
        btInicio.setContentAreaFilled(false);
        btInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btInicio.setFocusPainted(false);
        btInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btInicio.setIconTextGap(15);
        btInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicioActionPerformed(evt);
            }
        });

        btHistoria.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btHistoria.setText("Historia clinica");
        btHistoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btHistoria.setBorderPainted(false);
        btHistoria.setContentAreaFilled(false);
        btHistoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHistoria.setFocusPainted(false);
        btHistoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btHistoria.setIconTextGap(15);
        btHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistoriaActionPerformed(evt);
            }
        });

        btLaboratorio.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btLaboratorio.setText("Laboratorio");
        btLaboratorio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btLaboratorio.setBorderPainted(false);
        btLaboratorio.setContentAreaFilled(false);
        btLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLaboratorio.setFocusPainted(false);
        btLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btLaboratorio.setIconTextGap(15);
        btLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLaboratorioActionPerformed(evt);
            }
        });

        btPACS.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btPACS.setText("PACS");
        btPACS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btPACS.setBorderPainted(false);
        btPACS.setContentAreaFilled(false);
        btPACS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPACS.setFocusPainted(false);
        btPACS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPACS.setIconTextGap(15);
        btPACS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPACSActionPerformed(evt);
            }
        });

        btFacturacion.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btFacturacion.setText("Facturacion");
        btFacturacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btFacturacion.setBorderPainted(false);
        btFacturacion.setContentAreaFilled(false);
        btFacturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFacturacion.setFocusPainted(false);
        btFacturacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btFacturacion.setIconTextGap(15);
        btFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFacturacionActionPerformed(evt);
            }
        });

        btCerrar.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btCerrar.setText("Cerrar Sesion");
        btCerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btCerrar.setBorderPainted(false);
        btCerrar.setContentAreaFilled(false);
        btCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCerrar.setFocusPainted(false);
        btCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCerrar.setIconTextGap(15);
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        image.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        image.setPreferredSize(new java.awt.Dimension(250, 250));

        btAgenda.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btAgenda.setText("Agendamiento");
        btAgenda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btAgenda.setBorderPainted(false);
        btAgenda.setContentAreaFilled(false);
        btAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAgenda.setFocusPainted(false);
        btAgenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAgenda.setIconTextGap(15);
        btAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgendaActionPerformed(evt);
            }
        });

        btUsuario.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btUsuario.setText("Usuarios");
        btUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btUsuario.setBorderPainted(false);
        btUsuario.setContentAreaFilled(false);
        btUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btUsuario.setFocusPainted(false);
        btUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btUsuario.setIconTextGap(15);
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btPACS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btLaboratorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btHistoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                                        .addComponent(btInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPACS, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pBase.setBackground(new java.awt.Color(255, 255, 255));
        pBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pBase.setLayout(new java.awt.CardLayout());

        pInicio.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        pPacienteHoy.setBackground(new java.awt.Color(255, 255, 255));
        pPacienteHoy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Citas del dia");

        lbCantidadDia.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lbCantidadDia.setText("Cantidad dia");

        javax.swing.GroupLayout pPacienteHoyLayout = new javax.swing.GroupLayout(pPacienteHoy);
        pPacienteHoy.setLayout(pPacienteHoyLayout);
        pPacienteHoyLayout.setHorizontalGroup(
            pPacienteHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPacienteHoyLayout.createSequentialGroup()
                .addGroup(pPacienteHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPacienteHoyLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lbCantidadDia, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPacienteHoyLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        pPacienteHoyLayout.setVerticalGroup(
            pPacienteHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPacienteHoyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbCantidadDia)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel1.add(pPacienteHoy);

        pPacientesEspera.setBackground(new java.awt.Color(255, 255, 255));
        pPacientesEspera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pendientes");

        lbCantidadPendientes.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lbCantidadPendientes.setText("Cantidad pendientes");

        javax.swing.GroupLayout pPacientesEsperaLayout = new javax.swing.GroupLayout(pPacientesEspera);
        pPacientesEspera.setLayout(pPacientesEsperaLayout);
        pPacientesEsperaLayout.setHorizontalGroup(
            pPacientesEsperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPacientesEsperaLayout.createSequentialGroup()
                .addGroup(pPacientesEsperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPacientesEsperaLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2))
                    .addGroup(pPacientesEsperaLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lbCantidadPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pPacientesEsperaLayout.setVerticalGroup(
            pPacientesEsperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPacientesEsperaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lbCantidadPendientes)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel1.add(pPacientesEspera);

        pAlerta.setBackground(new java.awt.Color(255, 255, 255));
        pAlerta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Alertas laboratorio");

        lbCantidadAlerta.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lbCantidadAlerta.setText("Cantidad Alertas");

        javax.swing.GroupLayout pAlertaLayout = new javax.swing.GroupLayout(pAlerta);
        pAlerta.setLayout(pAlertaLayout);
        pAlertaLayout.setHorizontalGroup(
            pAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlertaLayout.createSequentialGroup()
                .addGroup(pAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlertaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4))
                    .addGroup(pAlertaLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lbCantidadAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pAlertaLayout.setVerticalGroup(
            pAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lbCantidadAlerta)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel1.add(pAlerta);

        pPendiente.setBackground(new java.awt.Color(255, 255, 255));
        pPendiente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("IA Pendientes");

        lbCantidadIA.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lbCantidadIA.setText("Cantidad IA");

        javax.swing.GroupLayout pPendienteLayout = new javax.swing.GroupLayout(pPendiente);
        pPendiente.setLayout(pPendienteLayout);
        pPendienteLayout.setHorizontalGroup(
            pPendienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPendienteLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPendienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCantidadIA, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        pPendienteLayout.setVerticalGroup(
            pPendienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPendienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCantidadIA)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel1.add(pPendiente);

        tblPacientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Pacientes", "Cedula", "Motivo", "Estado"
            }
        ));
        tblPacientes.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        jScrollPane1.setViewportView(tblPacientes);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel5.setText("Citas");

        javax.swing.GroupLayout pInicioLayout = new javax.swing.GroupLayout(pInicio);
        pInicio.setLayout(pInicioLayout);
        pInicioLayout.setHorizontalGroup(
            pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1544, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(pInicioLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pInicioLayout.setVerticalGroup(
            pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pBase.add(pInicio, "pantallaInicio");

        pPerfil.setBackground(new java.awt.Color(255, 255, 255));
        pPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbBienvenida.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lbBienvenida.setText("Bienvenido usuario");

        Icono.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Icono.setPreferredSize(new java.awt.Dimension(120, 120));

        lbFechaHora.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lbFechaHora.setText("Fecha:");

        javax.swing.GroupLayout pPerfilLayout = new javax.swing.GroupLayout(pPerfil);
        pPerfil.setLayout(pPerfilLayout);
        pPerfilLayout.setHorizontalGroup(
            pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbFechaHora)
                .addGap(18, 18, 18)
                .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        pPerfilLayout.setVerticalGroup(
            pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPerfilLayout.createSequentialGroup()
                .addGroup(pPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPerfilLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbFechaHora))
                    .addGroup(pPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPerfilLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbBienvenida)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicioActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) pBase.getLayout();
        layout.show(pBase, "pantallaInicio");
    }//GEN-LAST:event_btInicioActionPerformed

    private void btHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistoriaActionPerformed
        //Obtiene el diseño actual del panel principal 'pBase' y lo convierte a CardLayout
        java.awt.CardLayout layout = (java.awt.CardLayout) pBase.getLayout();
        //Le indica al CardLayout que traiga al frente la tarjeta que fue registrada bajo el nombre "pantallaHistoriaClinica".
        //Esto muestra visualmente la clase vHistoriaClinica que habiamos instanciado al inicio.
        layout.show(pBase, "pantallaHistoriaClinica");
    }//GEN-LAST:event_btHistoriaActionPerformed

    private void btLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLaboratorioActionPerformed
        //Obtiene el diseño actual del panel principal 'pBase' y lo convierte a CardLayout
        java.awt.CardLayout layout = (java.awt.CardLayout) pBase.getLayout();
        //Le indica al CardLayout que traiga al frente la tarjeta que fue registrada bajo el nombre "pantallaLaboratorio".
        //Esto muestra visualmente la clase vHistoriaClinica que habiamos instanciado al inicio.
        layout.show(pBase, "pantallaLaboratorio");
    }//GEN-LAST:event_btLaboratorioActionPerformed

    private void btPACSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPACSActionPerformed
        //Obtiene el diseño actual del panel principal 'pBase' y lo convierte a CardLayout
        java.awt.CardLayout layout = (java.awt.CardLayout) pBase.getLayout();
        //Le indica al CardLayout que traiga al frente la tarjeta que fue registrada bajo el nombre "pantallaPACS".
        //Esto muestra visualmente la clase vPACS que habiamos instanciado al inicio.
        layout.show(pBase, "pantallaPACS");
    }//GEN-LAST:event_btPACSActionPerformed

    private void btFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFacturacionActionPerformed
        //Obtiene el diseño actual del panel principal 'pBase' y lo convierte a CardLayout
        java.awt.CardLayout layout = (java.awt.CardLayout) pBase.getLayout();
        //Le indica al CardLayout que traiga al frente la tarjeta que fue registrada bajo el nombre "pantallaFacturacion".
        //Esto muestra visualmente la clase vFacturacion que habiamos instanciado al inicio.
        layout.show(pBase, "pantallaFacturacion");
    }//GEN-LAST:event_btFacturacionActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        //Obtiene el diseño actual del panel principal 'pBase' y lo convierte a CardLayout
        java.awt.CardLayout layout = (java.awt.CardLayout) pBase.getLayout();
        //Le indica al CardLayout que traiga al frente la tarjeta que fue registrada bajo el nombre "pantallaSesion".
        //Esto muestra visualmente la clase vSesion que habiamos instanciado al inicio.
        layout.show(pBase, "pantallaSesion");
        mostrarBarraYMenu(false);
    }//GEN-LAST:event_btCerrarActionPerformed

    private void btAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgendaActionPerformed
        //Obtiene el diseño actual del panel principal 'pBase' y lo convierte a CardLayout
        java.awt.CardLayout layout = (java.awt.CardLayout) pBase.getLayout();
        //Le indica al CardLayout que traiga al frente la tarjeta que fue registrada bajo el nombre "pantallaAgendamiento".
        //Esto muestra visualmente la clase vAgendamiento que habiamos instanciado al inicio.
        layout.show(pBase, "pantallaAgendamiento");
    }//GEN-LAST:event_btAgendaActionPerformed

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
        //Obtiene el diseño actual del panel principal 'pBase' y lo convierte a CardLayout
        java.awt.CardLayout layout = (java.awt.CardLayout) pBase.getLayout();
        //Le indica al CardLayout que traiga al frente la tarjeta que fue registrada bajo el nombre "pantallaUsuario".
        //Esto muestra visualmente la clase vUsuario que habiamos instanciado al inicio.
        layout.show(pBase, "pantallaUsuario");
    }//GEN-LAST:event_btUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono;
    private javax.swing.JButton btAgenda;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btFacturacion;
    private javax.swing.JButton btHistoria;
    private javax.swing.JButton btInicio;
    private javax.swing.JButton btLaboratorio;
    private javax.swing.JButton btPACS;
    private javax.swing.JButton btUsuario;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbBienvenida;
    private javax.swing.JLabel lbCantidadAlerta;
    private javax.swing.JLabel lbCantidadDia;
    private javax.swing.JLabel lbCantidadIA;
    private javax.swing.JLabel lbCantidadPendientes;
    public javax.swing.JLabel lbFechaHora;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel pAlerta;
    private javax.swing.JPanel pBase;
    private javax.swing.JPanel pInicio;
    private javax.swing.JPanel pPacienteHoy;
    private javax.swing.JPanel pPacientesEspera;
    private javax.swing.JPanel pPendiente;
    private javax.swing.JPanel pPerfil;
    private javax.swing.JTable tblPacientes;
    // End of variables declaration//GEN-END:variables

//Metodo para ocultar el menu lateral al momento de poner el programa
    public void mostrarBarraYMenu(boolean visible) {
        menu.setVisible(visible);
        pPerfil.setVisible(visible);
    }
//Metodo para inicializar las vistas

    private void inicializarVistas() {
        //Se agrega el objeto vHistoriaClinica
        vHistoriaClinica vistaHistoria = new vHistoriaClinica();
        //Se agrega el objeto vFacturacion
        vFacturacion vistaFacturacion = new vFacturacion();
        //Se agrega el objeto vAgendamiento
        vAgendamiento vistaAgendamiento = new vAgendamiento();
        //Se agrega el objeto vLaboratorio
        vLaboratorio vistaLaboratorio = new vLaboratorio();
        //Se agrega el objeto vPACS
        vPACS vistaPACS = new vPACS();
        //Se agrega el objeto vSesion
        vSesion vistaSesion = new vSesion();
        //Se agrega el objeto vSesion
        vUsuarios vistaUsuario = new vUsuarios();
        //Aqui se le dice al panel agregado que agregue la vista del panel vHistoriaclinica y se le pone una etiqueta
        //Agrega el panel vistaHistoriaClinica al contenedor principal llamado pBase.
        //Como pBase es un CardLayout, el segundo parametro ("pantallaHistoriaClinica") funciona como un alias o identificador unico.
vPacientes vistaPacientes = new vPacientes();

javax.swing.JTabbedPane pestanasPersonas =
        new javax.swing.JTabbedPane();

// Agrega los campos y botones del formulario a la pestaña.
pestanasPersonas.addTab(
        "Pacientes",
        vistaPacientes.getContentPane()
);

// Libera la ventana; su contenido ya está en la pestaña.
vistaPacientes.dispose();

pestanasPersonas.addTab("Personal", vistaUsuario);
        pBase.add(pInicio, "pantallaInicio");
        pBase.add(vistaHistoria, "pantallaHistoriaClinica");
        pBase.add(vistaFacturacion, "pantallaFacturacion");
        pBase.add(vistaAgendamiento, "pantallaAgendamiento");
        pBase.add(vistaLaboratorio, "pantallaLaboratorio");
        pBase.add(vistaPACS, "pantallaPACS");
        pBase.add(vistaSesion, "pantallaSesion");
        pBase.add(pestanasPersonas, "pantallaUsuario");
        // Oculta la barra y menú al inicio
        mostrarBarraYMenu(false);
        // Muestra la pantalla de inicio de sesión por defecto
        CardLayout cl = (CardLayout) pBase.getLayout();
        cl.show(pBase, "pantallaSesion");
    }

//Metodo para ajustar las imagenes a los botones
    private void ajustarIcono(javax.swing.JButton boton, String rutaImagen) {
        try {
            javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource(rutaImagen));
            java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH);
            boton.setIcon(new javax.swing.ImageIcon(imagenEscalada));
        } catch (Exception e) {
            System.out.println("No se pudo cargar la imagen: " + rutaImagen);
        }
    }

//Metodo para ajustar las imagenes al label
    private void ajustarImagenLabel(javax.swing.JLabel label, String rutaImagen) {
        try {
            javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource(rutaImagen));
            int ancho = label.getPreferredSize().width;
            int alto = label.getPreferredSize().height;
            java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH);
            label.setIcon(new javax.swing.ImageIcon(imagenEscalada));
        } catch (Exception e) {
            System.out.println("No se pudo cargar la imagen del Label: " + rutaImagen);
        }
    }

//Metodo para poner las imagenes en los label y botones
    private void iconos() {
        ajustarImagenLabel(image, "/imagenes/icono.png");
        ajustarImagenLabel(Icono, "/imagenes/medico.png");
        ajustarIcono(btInicio, "/imagenes/casa.png");
        ajustarIcono(btHistoria, "/imagenes/historia clinica.png");
        ajustarIcono(btLaboratorio, "/imagenes/laboratorio.png");
        ajustarIcono(btPACS, "/imagenes/PACS.png");
        ajustarIcono(btFacturacion, "/imagenes/facturacion.png");
        ajustarIcono(btAgenda, "/imagenes/agenda.png");
        ajustarIcono(btCerrar, "/imagenes/cerrar.png");
        ajustarIcono(btUsuario, "/imagenes/usuario.png");
    }

//Metodo para el panel de bienvendia
    private void configurarBienvenida() {
        //Aqui vamos a agregar los metodos para obtener el que entre
        String nombre = "Dr. Esteban López";
        String rol = "Médico General";

        lbBienvenida.setText("<html>¡Bienvenido!<br>" + nombre + " | " + rol + "</html>");
    }

//Metodo para tener la fehca y el reloj
    private void iniciarReloj() {
        java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("EEEE, dd MMM yyyy | hh:mm:ss a");
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                java.time.LocalDateTime ahora = java.time.LocalDateTime.now();
                String textoFechaHora = ahora.format(formato);
                textoFechaHora = textoFechaHora.substring(0, 1).toUpperCase() + textoFechaHora.substring(1);

                lbFechaHora.setText(textoFechaHora);
            }
        });
        timer.start();
    }

//Metodo para la configuracion de las tarjetas de resumen
    private void configurarTarjetas() {
        //Agregar metodos
        //Datos de prueba
        int pacientesHoy = 12;
        int enEspera = 3;
        String alertasLab = "1";
        int sugerenciasIA = 2;
        lbCantidadDia.setText(String.valueOf(pacientesHoy));
        lbCantidadPendientes.setText(String.valueOf(enEspera));
        lbCantidadAlerta.setText(alertasLab);
        lbCantidadIA.setText(String.valueOf(sugerenciasIA));
    }

    public void configurarPermisosSegunRol(String rol) {
        // 'Inicio' y 'Cerrar Sesión' siempre permanecen activos para todos

        String rolNormalizado = rol.trim().toLowerCase();

        //Bloquear por defecto todos los botones restringidos
        btHistoria.setEnabled(false);
        btLaboratorio.setEnabled(false);
        btPACS.setEnabled(false);
        btFacturacion.setEnabled(false);
        btAgenda.setEnabled(false);
        btUsuario.setEnabled(false);

        //Habilitar únicamente los módulos permitidos según el rol
        switch (rolNormalizado) {
            case "administrador":
            case "admin":
                btHistoria.setEnabled(true);
                btLaboratorio.setEnabled(true);
                btPACS.setEnabled(true);
                btFacturacion.setEnabled(true);
                btAgenda.setEnabled(true);
                btUsuario.setEnabled(true);
                break;

            case "medico":
            case "médico":
                btHistoria.setEnabled(true);
                btLaboratorio.setEnabled(true);
                btPACS.setEnabled(true);
                break;

            case "recepcion":
            case "recepción":
            case "recepcionista":
                btFacturacion.setEnabled(true);
                btAgenda.setEnabled(true);
                break;

            default:
                System.out.println("Rol no reconocido: " + rol);
                break;
        }
    }

//Funcion para guardar la configuracion de todo el panel
    public void estilo() {
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        menu.setBackground(Color.decode("#A3C9A8"));
        iconos();
        configurarBienvenida();
        iniciarReloj();
        configurarTarjetas();
        inicializarVistas();
    }

    public javax.swing.JPanel getpBase() {
        return pBase;
    }
}
